- name: Install S3cmd
  apt:
    name: s3cmd
    state: present

- name: Copy .s3cfg file to home directory
  copy:
    src: .s3cfg.j2
    dest: "{{ ansible_env.HOME }}/.s3cfg"
    mode: 0600

- name: Copy backup script to target machine
  copy:
    src: pgback_script.sh.j2
    dest: /usr/local/bin/pgback_script.sh
    mode: 0755

- name: Add PostgreSQL Backup cron job
  cron:
    name: PostgreSQL Backup
    minute: 0
    hour: 1
    job: /usr/local/bin/pgback_script.sh
